/* Feature groupings for the manual input form */
export const FEATURE_GROUPS = [
  { title: 'Flow Information', features: ['Destination Port', 'Flow Duration'] },
  { title: 'Packet Counts', features: ['Total Fwd Packets', 'Total Backward Packets'] },
  { title: 'Packet Lengths', features: ['Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std'] },
  { title: 'Flow Rates', features: ['Flow Bytes/s', 'Flow Packets/s'] },
  { title: 'Inter-Arrival Time (IAT)', features: ['Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min'] },
  { title: 'PSH & URG Flags', features: ['Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags'] },
  { title: 'Header & Packet Stats', features: ['Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance'] },
  { title: 'TCP Flags', features: ['FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count'] },
  { title: 'Ratios & Averages', features: ['Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1'] },
  { title: 'Bulk Statistics', features: ['Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate'] },
  { title: 'Subflow Features', features: ['Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes'] },
  { title: 'Window & Segment', features: ['Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward'] },
  { title: 'Active / Idle', features: ['Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min'] },
];

/* All 78 features in exact training order */
export const ALL_FEATURES = [
  'Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets',
  'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max',
  'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std',
  'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean',
  'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean',
  'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean',
  'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
  'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
  'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length',
  'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length',
  'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
  'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
  'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
  'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
  'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk',
  'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk',
  'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes',
  'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
  'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
  'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
  'Idle Std', 'Idle Max', 'Idle Min',
];

/* Sample data for quick testing */
export const SAMPLE_DATA = {
  'Destination Port': 443, 'Flow Duration': 120000, 'Total Fwd Packets': 10,
  'Total Backward Packets': 8, 'Total Length of Fwd Packets': 1500,
  'Total Length of Bwd Packets': 3200, 'Fwd Packet Length Max': 250,
  'Fwd Packet Length Min': 40, 'Fwd Packet Length Mean': 150, 'Fwd Packet Length Std': 45,
  'Bwd Packet Length Max': 1460, 'Bwd Packet Length Min': 40, 'Bwd Packet Length Mean': 400,
  'Bwd Packet Length Std': 350, 'Flow Bytes/s': 39166.67, 'Flow Packets/s': 150,
  'Flow IAT Mean': 15000, 'Flow IAT Std': 5000, 'Flow IAT Max': 50000, 'Flow IAT Min': 100,
  'Fwd IAT Total': 120000, 'Fwd IAT Mean': 13333, 'Fwd IAT Std': 4000, 'Fwd IAT Max': 30000,
  'Fwd IAT Min': 50, 'Bwd IAT Total': 100000, 'Bwd IAT Mean': 14285, 'Bwd IAT Std': 5000,
  'Bwd IAT Max': 40000, 'Bwd IAT Min': 100, 'Fwd PSH Flags': 0, 'Bwd PSH Flags': 0,
  'Fwd URG Flags': 0, 'Bwd URG Flags': 0, 'Fwd Header Length': 320, 'Bwd Header Length': 256,
  'Fwd Packets/s': 83.33, 'Bwd Packets/s': 66.67, 'Min Packet Length': 40,
  'Max Packet Length': 1460, 'Packet Length Mean': 261.11, 'Packet Length Std': 330,
  'Packet Length Variance': 108900, 'FIN Flag Count': 1, 'SYN Flag Count': 1,
  'RST Flag Count': 0, 'PSH Flag Count': 4, 'ACK Flag Count': 16, 'URG Flag Count': 0,
  'CWE Flag Count': 0, 'ECE Flag Count': 0, 'Down/Up Ratio': 0.8, 'Average Packet Size': 261.11,
  'Avg Fwd Segment Size': 150, 'Avg Bwd Segment Size': 400, 'Fwd Header Length.1': 320,
  'Fwd Avg Bytes/Bulk': 0, 'Fwd Avg Packets/Bulk': 0, 'Fwd Avg Bulk Rate': 0,
  'Bwd Avg Bytes/Bulk': 0, 'Bwd Avg Packets/Bulk': 0, 'Bwd Avg Bulk Rate': 0,
  'Subflow Fwd Packets': 10, 'Subflow Fwd Bytes': 1500, 'Subflow Bwd Packets': 8,
  'Subflow Bwd Bytes': 3200, 'Init_Win_bytes_forward': 8192, 'Init_Win_bytes_backward': 14600,
  'act_data_pkt_fwd': 5, 'min_seg_size_forward': 32, 'Active Mean': 50000,
  'Active Std': 10000, 'Active Max': 60000, 'Active Min': 40000,
  'Idle Mean': 0, 'Idle Std': 0, 'Idle Max': 0, 'Idle Min': 0,
};
